[project]
name = "taubenturret"
version = "1.0.0"
description = "An automated, computer vision driven water turret system for targeted pigeon deterrence."
authors = [{ name = "Michael Weber", email = "mweberw@pm.me" }]
readme = "README.md"
keywords = ['python']
license = { text = "GPLv3" }
requires-python = ">=3.10,<4.0"
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "python-dotenv>=1.2.2",
    "numpy>=2.2.6",
    "opencv-python>=4.8.0",
    "rpi-hardware-pwm>=0.2.2",
    "fastapi>=0.136.1",
    "uvicorn>=0.46.0",
]

[project.scripts]
taubenturret = "taubenturret.main:main"

[project.urls]
Homepage = "https://github.com/MLWeber/taubenturret"
Repository = "https://github.com/MLWeber/taubenturret"
Documentation = "https://github.com/MLWeber/taubenturret"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pre-commit>=4.5.1",
    "tox-uv>=1.33.4",
    "mypy>=1.19.1",
    "ruff>=0.15.7",
    "types-requests>=2.33.0.20260408",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["taubenturret"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.mypy]
files = ["taubenturret"]
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true

[[tool.mypy.overrides]]
module = ["picamera2.*", "picamera2.encoders.*", "picamera2.outputs.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
target-version = "py310"
line-length = 120
fix = true

[tool.ruff.lint]
select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E",
    "W",
    # pyflakes
    "F",
    # pygrep-hooks
    "PGH",
    # pyupgrade
    "UP",
    # ruff
    "RUF",
    # tryceratops
    "TRY",
]
ignore = [
    # DoNotAssignLambda
    "E731",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.ruff.format]
preview = true
